 package com.idep.proposal.util;
 
 import java.math.BigInteger;
 import java.security.MessageDigest;
 import java.security.NoSuchAlgorithmException;
 
 public class SHA512Encryption {
   public static String encryptThisStringSHA512(String input) {
     try {
       MessageDigest md = MessageDigest.getInstance("SHA-512");
       byte[] mdbytes = md.digest(input.getBytes());
       StringBuffer sb = new StringBuffer();
       for (int i = 0; i < mdbytes.length; i++)
         sb.append(Integer.toString((mdbytes[i] & 0xFF) + 256, 16).substring(1)); 
       System.out.println("Hex format : " + sb.toString());
       StringBuffer hexString = new StringBuffer();
       for (int j = 0; j < mdbytes.length; j++)
         hexString.append(Integer.toHexString(0xFF & mdbytes[j])); 
       System.out.println("Hex format : " + hexString.toString());
       return hexString.toString().toLowerCase();
     } catch (NoSuchAlgorithmException e) {
       throw new RuntimeException(e);
     } 
   }
   
   public static String encryptThisString(String input) {
     try {
       MessageDigest md = MessageDigest.getInstance("SHA-512");
       byte[] messageDigest = md.digest(input.getBytes());
       BigInteger no = new BigInteger(1, messageDigest);
       String hashtext = no.toString(16);
       while (hashtext.length() < 128)
         hashtext = "0" + hashtext; 
       return hashtext.toLowerCase();
     } catch (NoSuchAlgorithmException e) {
       throw new RuntimeException(e);
     } 
   }
   
   public static void main(String[] args) throws NoSuchAlgorithmException {
     System.out.println("HashCode Generated by SHA-512 for: ");
     String s1 = "an7rIU|PROP000C58802|23783|Kotak Car Care|Sadsf|rajat.asatkar@slkglobalsolution.com|||||||||||8MUr8LS7";
     System.out.println("\n" + s1 + " : " + encryptThisString(s1) + " length + ");
   }
 }


