 package com.idep.service.payment.util;
 
 import com.fasterxml.jackson.databind.ObjectMapper;
 import org.apache.log4j.Logger;
 
 public class PaymentConstant {
   static Logger log = Logger.getLogger(PaymentConstant.class.getName());
   
   static ObjectMapper objectMapper = new ObjectMapper();
   
   public static Properties PROPERTIES = new Properties();
   public static final String PAYMENT_CONSTANT_DOCUMENT = "PaymentConstantConfig";
   public static final String PAYMENT_GATEWAY_BILLDESK = "billdesk";
   public static final String PAYMENT_RETURN_URL = "returnUrl";
   public static final String PAYMENT_URL = "paymentURL";
   public static final String PAYMENT_PARAM_LIST = "paramterList";
   public static final String PAYMENT_VALUE = "value";
   public static final String PAYMENT_CHECKSUM_STATUS = "checksumStatus";
   public static final int PAYMENT_PARAM_INDEX = 1;
   public static final String MASTER_PAYMENT_RESPONSE = "MasterPaymentConfigDetails";
   public static final String REDIRECT_URL_CONFIG_DOC = "REDIRECT_URL_CONFIG_DOC";
   public static final String MASTER_PAYMENT_RESPONSE_WORDPRESS = "MasterPaymentConfigDetails-wordpress";
   public static final String RESPONSEMASTERLIST = "masterParams";
   public static final String RENDER_TYPE = "renderType";
   public static final String ENCRYPTION_TYPE = "encryptionType";
   public static final String ENCRYPTION_FORM_PARAM_KEY = "encryptionFormParamKey";
   public static final String RENDER_TYPE_LIST = "list";
   public static final String RENDER_TYPE_CONCAT = "concat";
   public static final String RENDER_CONCAT_PARAM_KEY = "concatParamKey";
   public static final String RENDER_FORMAT_CONCAT = "concatFormat";
   public static final String RENDER_CONCAT_DELIMITER = "delimiter";
   public static final String RESPONSE_SUCCESS_PARAMTYPE = "success";
   public static final String RESPONSE_FAIL_PARAMTYPE = "failure";
   public static final String SUCCESS = "success";
   public static final String FAILURE = "failure";
   public static final String RESEPONSE_DOC_TYPE = "PaymentResponseDetails";
   public static final String REQUEST_DOC_TYPE = "PaymentRequestDetails";
   public static final String RESPONSE_SEQ_PREFIX = "paymentResponseId";
   public static final String REQUEST_SEQ_PREFIX = "paymentRequestId";
   public static final String RESPONSE_SEQ = "SEQPAYMENTRES";
   public static final String REQUEST_SEQ = "SEQPAYMENTREQ";
   public static final String DOCID_CONFIG = "DocumentIDConfig";
   public static final String SUBMIT_PARAM_APPROACH = "submitParamApproach";
   public static final String SUBMIT_APPROACH_URLAPPEND = "urlappend";
   public static final String SUBMIT_PARAM_LIST = "submitParams";
   public static final String SUBMIT_PARAM_KEY = "name";
   public static final String SUBMIT_PARAM_VALUE = "value";
   public static final String REQUEST = "request";
   public static final String RESPONSE = "response";
   public static final String PAY_REQ_REF_ID = "payReqRefId";
   public static final String PAYMENT_REQUEST = "paymentRequest";
   public static final String PAYMENT_RESPONSE = "paymentResponse";
   public static final String DB_BUCKET_POLICY_TRANS = "policyTransaction";
   public static final String DB_BUCKET_SERVER_CONF = "serverConfig";
   public static final String CARRIER_CONFIG = "CarrierConfig";
   public static final String PAYMENT_RESPONSE_PARAM_CONFIG = "PaymentResponseParamConfig";
   public static final String PAYMENT_REQUEST_PARAM_CONFIG = "PaymentRequestParamConfig";
   public static final String PAYMENT_REQUEST_REFERENCE_KEY = "payReqRefKey";
   public static final String PAYMENT_REQUEST_REFERENCE_VAL = "payReqRefVal";
   public static final String PAYMENT_METHOD_TYPE_GET = "GET";
   public static final String PAYMENT_METHOD_TYPE_POST = "POST";
   public static final String HTTP_METHOD_TYPE_POST = "POST";
   public static final String SERVICE_URL_CONFIG_DOC = "ServiceURLConfig";
   public static final String WEBHOST_CONFIG_DOC = "WEBHOSTConfig";
   public static final String SERVICE_URL = "MServiceURL";
   public static final String MASTER_SERVICE_URL = "masterService";
   public static final String TRANS_NAME = "transactionName";
   public static final String METHOD_HEADER = "methodname";
   public static final String MESSAGE_ID = "messageId";
   public static final String LEAD_MESSAGE_ID = "leadMessageId";
   public static final String VALIDATE_PAY_STATUS_TRANS_NAME = "validatePaymentStatus";
   public static final String SUCC_CONFIG_CODE = "successCode";
   public static final String SUCC_CONFIG_MSG = "successMessage";
   public static final String FAIL_CONFIG_CODE = "failureCode";
   public static final String FAIL_CONFIG_MSG = "failureMessage";
   public static final String ERROR_CONFIG_CODE = "errorCode";
   public static final String ERROR_CONFIG_MSG = "errorMessage";
   public static final String RES_CODE = "responseCode";
   public static final String RES_MSG = "message";
   public static final String RES_DATA = "data";
   public static final String RESPONSE_CONFIG_DOC = "ResponseMessages";
   public static final String BUSINESS_LINES_ID = "{\"life\":1, \"bike\":2, \"car\":3, \"health\":4, \"travel\":5,\"home\":7,\"personalaccident\":8}";
   public static final String BUSINESS_LINES_NAME = "{\"1\":\"life\", \"2\":\"bike\", \"3\":\"car\", \"4\":\"health\", \"5\":\"travel\", \"7\":\"home\", \"8\":\"personalaccident\"}";
   public static final String CREATE_POLICY_TRANS_NAME = "{\"life\":\"createLifePolicy\", \"bike\":\"createBikePolicy\", \"car\":\"createCarPolicy\", \"health\":\"createHealthPolicy\", \"travel\":\"createTravelPolicy\", \"personalaccident\":\"createPersonalAccidentPolicy\",\"home\":\"createHomePolicy\"}";
   public static final String PROPOSAL_RESP_NODE = "{\"life\":\"lifeProposalResponse\", \"bike\":\"bikeProposalResponse\", \"car\":\"carProposalResponse\", \"health\":\"healthProposalResponse\", \"travel\":\"travelProposalResponse\", \"personalaccident\":\"personalAccidentProposalResponse\",\"home\":\"homeProposalResponse\"}";
   public static final String PROPOSAL_REQ_DOC_TYPE = "{\"life\":\"lifeProposalRequest\", \"bike\":\"bikeProposalRequest\", \"car\":\"carProposalRequest\", \"health\":\"healthProposalRequest\", \"travel\":\"travelProposalRequest\", \"personalaccident\":\"personalAccidentProposalRequest\",\"home\":\"homeProposalRequest\"}";
   public static final String DEVICE_ID = "deviceId";
   public static final String DB_QUERY_PROPOSAL_DOC_ID_LIFE = "select meta().id as documentId from PolicyTransaction where documentType='lifeProposalRequest' and paymentRequest.payReqRefVal=$1";
   public static final String DB_QUERY_PROPOSAL_DOC_ID_BIKE = "select meta().id as documentId from PolicyTransaction where documentType='bikeProposalRequest' and paymentRequest.payReqRefVal=$1";
   public static final String DB_QUERY_PROPOSAL_DOC_ID_CAR = "select meta().id as documentId from PolicyTransaction where documentType='carProposalRequest' and paymentRequest.payReqRefVal=$1";
   public static final String DB_QUERY_PROPOSAL_DOC_ID_HEALTH = "select meta().id as documentId from PolicyTransaction where documentType='healthProposalRequest' and paymentRequest.payReqRefVal=$1";
   public static final String DB_QUERY_PROPOSAL_DOC_ID_TRAVEL = "select meta().id as documentId from PolicyTransaction where documentType='travelProposalRequest' and paymentRequest.payReqRefVal=$1";
   public static final String P365_IntegrationList = "P365IntegrationList";
   public static final String DEVICE_ID_VALUE = "ABCD12345";
   public static final String PAYRESSTATUSCODE = "&statusCode=PE1020";
   public static final String DB_QUERY_PROPOSAL_DOC_ID_PERSONAL_ACCIDENT = "select meta().id as documentId from PolicyTransaction where documentType='personalAccidentProposalRequest' and paymentRequest.payReqRefVal=$1";
   public static final String DB_QUERY_PROPOSAL_DOC_ID_HOME = "select meta().id as documentId from PolicyTransaction where documentType='homeProposalRequest' and paymentRequest.payReqRefVal=$1";
   public static final String P365RES100 = "P365RES100";
 }


