 package com.idep.proposal.util;
 
 import java.math.BigInteger;
 import java.security.MessageDigest;
 import java.security.NoSuchAlgorithmException;
 
 public class SHAEncryption {
   public static String encryptThisString(String input) {
     try {
       MessageDigest md = MessageDigest.getInstance("SHA-512");
       byte[] messageDigest = md.digest(input.getBytes());
       BigInteger no = new BigInteger(1, messageDigest);
       String hashtext = no.toString(16);
       while (hashtext.length() < 32)
         hashtext = "0" + hashtext; 
       return hashtext.toUpperCase();
     } catch (NoSuchAlgorithmException e) {
       throw new RuntimeException(e);
     } 
   }
   
   public static void main(String[] args) throws NoSuchAlgorithmException {
     System.out.println("HashCode Generated by SHA-512 for: ");
     String s1 = "SLKGLOBALSOLUTION|1222101044467|mCpK5tFioXsa0fI7L6aQPQ==|S001";
     System.out.println("\n" + s1 + " : " + encryptThisString(s1));
   }
 }


