package com.idep.lifequote.util;

/**
 * 
 * @author yogesh.shisode
 *
 */
public class LifeQuoteConstants {
	 public static final String DEFAULT_LOG_DATA = "defaultLogData";
	  public static final String INPUT_MESSAGE = "inputMessage";
	  public static final String UNIQUE_KEY = "uniqueKey";
	  public static final String JMSCORRELATION_ID = "JMSCorrelationID";
	  public static final String CORRELATION_ID = "correlationId";
	  public static final String SOURCEQUEUENAME = "sourceQName";
	  public static final String LIFE_CARRIERS_Q = "LifeCarrierQList";
	  public static final String LIFE_PRODUCT_QUERY_CONFIG = "LifeProductQueryConfig";
	  public static final String RES_Q_LIST = "carrierResQ";
	  public static final String REQ_Q_LIST = "carrierReqQ";
	  public static final String PRODUCT_INFO = "productInfo";
	  public static final String QUOTE_ID = "QUOTE_ID";
	  public static final String ENCRYPT_QUOTE_ID = "encryptedQuoteId";
	  public static final String STATUS	= "status";
	  public static final String CARRIER_ID	= "carrierId";
	  public static final String PRODUCT_ID	= "productId";
	  public static final String CARRIER_PRODUCT_ID	= "carrierProductId";
	  public static final String DOCID_CONFIG	= "DocumentIDConfig";
	  public static final String UI_CARQUOTEREQUEST = "quoteInputRequest";
	  public static final String PRODUCT_PICKING_QUERY = "productPickingQuery";
	  public static final String PRODUCT_PICKING_QUERY_PARAMS = "productParams";
	  
	  public static final String SUCC_CONFIG_CODE = "successCode";
	  public static final String SUCC_CONFIG_MSG = "successMessage";
	  public static final String FAIL_CONFIG_CODE = "failureCode";
	  public static final String FAIL_CONFIG_MSG = "failureMessage";
	  public static final String ERROR_CONFIG_CODE = "errorCode";
	  public static final String ERROR_CONFIG_MSG = "errorMessage";
	  public static final String PRD_NOT_FOUND_CODE = "quotePrdNotFoundCode";
	  public static final String PRD_NOT_FOUND_MSG = "quotePrdNotFoundMessage";
	  public static final String QUOTE_DATA_MISSING_CODE = "quoteInputMissingCode";
	  public static final String QUOTE_DATA_MISSING_MSG = "quoteInputMissingMessage";
	  public static final String QUOTE_DATA_RANGE_CODE = "quoteInputRangeValCode";
	  public static final String QUOTE_DATA_RANGE_MSG = "quoteInputRangeValMessage";
	  public static final String RESPONSE_CONFIG_DOC = "ResponseMessages";
	  //public static final String DROOL_URL_CONFIG = "ExternalServiceURLConfig";
	  public static final String DROOL_URL_CONFIG = "RuleEngineURLConfig";
	  public static final String LIFE_QUOTE_TYPE = "DroolQuoteType1";
	  public static final String BIKE_QUOTE_TYPE = "DroolQuoteType2";
	  public static final String CAR_QUOTE_TYPE = "DroolQuoteType3";
	  public static final String HEALTH_QUOTE_TYPE = "DroolQuoteType4";
	  public static final String QUOTE_REQ_PROPERTY = "quoteRequest";
	  public static final String QUOTE_RES_CODE = "responseCode";
	  public static final String QUOTE_RES_MSG = "message";
	  public static final String QUOTE_RES_DATA = "data";
	  public static final String REQUESTFLAG = "reqFlag";
	  public static final String LIFE_CARRIER_Q_LIST = "LifeCarrierQList";
	  public static final String LIFE_PREMIUM_RATE_CONFIG = "LifePremiumRateConfigurations";
	  public static final String LIFE_QUOTE_CONFIG = "LifeQuoteConfig";
	  //public static final String RES_Q_LIST = "resQList";
	  public static final String Q_NAMES = "qnames";
	  public static final String MSG_ID = "messageId";
	  public static final String COUNTER = "counter";
	  public static final String QUOTE_VALIDATIONS = "QuoteValidations";
	  public static final String FALSE = "False";
	  public static final String TRUE = "True";
	  public static final String EXCEPTION = "Exception";
	  public static final String QUOTE_TYPE = "DroolQuoteType";
	  public static final String QUOTE_URL = "quoteURL";
	  public static final String DROOLS_SHOWROOM_PRICE = "showRoomPrice";
	  public static final String DROOLS_INSURER_INDEX = "insurerIndex";
	  public static final String DROOLS_SUM_INSURED = "sumInsured";
	  public static final String DROOLS_HIGHER_SUM_ASSURED = "maxSumInsured";
	  public static final String DROOLS_LOWER_SUM_ASSURED = "minSumInsured";
	  public static final String DROOLS_RESULTS_NODE = "results";
	  public static final String DROOLS_RESULT_NODE = "result";
	  public static final String DROOLS_ELEMENT_NODE = "element";
	  public static final String DROOLS_VALUE_NODE = "value";
	  public static final int DROOLS_RESULT_ITEM_NO = 1;
	  public static final String DROOLS_AUTH_HEADER = "Authorization";
	  public static final String DROOLS_AUTH_DETAILS = "Basic a2llc2VydmVyOmtpZXNlcnZlcjEh";
	  public static final String DROOLS_CONTENT_TYPE_HEADER = "X-KIE-ContentType";
	  public static final String DROOLS_CONTENT_TYPE = "JSON";
	  public static final String DROOLS_HTTP_METHOD = "POST";
	  public static final String DROOLS_ACCEPT_TYPE = "application/json";
	  public static final String DROOLS_PAYOUT_TYPE = "payoutType";
	  public static final String CAMEL_HTTP_METHOD = "CamelHttpMethod";
	  public static final String CAMEL_HTTP_PATH = "CamelHttpPath";
	  public static final String CAMEL_ACCEPT_CONTENT_TYPE = "CamelAcceptContentType";
	  public static final String SERVICE_QUOTE_TYPE = "quoteType";
	  public static final String SERVICE_QUOTE_PARAM = "quoteParam";
	  public static final String SERVICE_VEHICLE_PARAM = "vehicleInfo";
	  public static final String SERVICE_HEALTH_RATING_PARAM = "ratingParam";
	  public static final String DROOLS_CARRIER = "carrier";
	  public static final String DROOLS_CARRIER_NAME = "carrierName";
	  public static final String DROOLS_CARRIERID = "carrierId";
	  public static final String DROOLS_PRODUCT_ID = "productId";
	  public static final String DROOLS_PRODUCT_NAME = "productName";
	  public static final String DROOLS_INSURANCE_TYPE = "insuranceType";
	  public static final String DROOLS_AGE_TYPE = "ageType";
	  public static final String DROOLS_PLANID = "planId";
	  public static final String DROOLS_PLAN_TYPE = "planType";
	  public static final String DROOLS_LIFEQUOTE_REQUEST_PART1 = "{\"insert\" : {\"object\" :{\"com.sutrr.quote.lifequotecalc.LifeQuoteRequest\":{\"quoteParamRequestList\":[";
	  public static final String DROOLS_LIFEQUOTE_REQUEST_PART2 = "],\"isExecuted\":false}},\"disconnected\" : false,\"out-identifier\" : \"0\",\"return-object\" : true,\"entry-point\" : \"DEFAULT\"}},";
	  public static final String DROOLS_LIFEQUOTE_REQUEST_PART3 = "{\"lookup\" : \"quoteksession\",\"commands\" : [ ";
	  public static final String DROOLS_LIFEQUOTE_REQUEST_PART4 = "{\"fire-all-rules\" : {\"max\" : -1,\"out-identifier\" : null}} , {\"get-objects\" : {\"out-identifier\" : \"objects\"}}]}";
	  public static final String FEATURES = "Features";
	  public static final String RATINGS = "Ratings";
	  public static final String PRODUCTS = "products";
	  public static final String RATINGS_LIST = "ratingsList";
	  public static final String FEATURES_LIST = "featuresList";
	  public static final String CATEGORY_MAP = "categoryMap";
	  public static final String DEFAULT_RISK_TYPE = "DefaultRiskType";
	  public static final String RISKS = "risks";
	  public static final String QUOTES = "quotes";
	  public static final String CAR_MASTER_RESPONSE = "com.sutrr.quote.carquotecalc.MasterResponse";
	  public static final String BIKE_MASTER_RESPONSE = "com.sutrr.quote.bikequotecalc.BikeMasterResponse";
	  public static final String QUOTE_RESPONSE_NODE = "quoteResponse";
	  public static final String ARRAY_LIST_NODE = "java.util.ArrayList";
	  public static final String DISCOUNT_LIST_NODE = "discountList";
	  public static final String EXCLUSIVE_DISCOUNT = "exclusiveDiscounts";
	  public static final String POLICY_TERM = "policyTerm";
	  public static final String PAYOUT_ID = "payoutId";
	  public static final String IS_ACTIVE_STATUS = "Y";
	  public static final int COMMON_PAYOUT_ID = 5;
	  public static final String UNCHECKED = "unchecked";
	  public static final String VALIDATION_ACTIVE = "validationActive";
	  public static final String Y = "Y";
	  public static final String LIFE_QUOTE_RESPONSE = "com.sutrr.quote.lifequotecalc.LifeQuoteResponse";
	  public static final String RIDER_LIST = "riderList";
	  public static final String MIN_ALLOWED_SUM_INSURED = "minAllowedSumInsured";
	  public static final String MAX_ALLOWED_SUM_INSURED = "maxAllowedSumInsured";
	  public static final String STAGE = "stage";
	  public static final String DEFAULT_LOG = "default";
	  
	  //public static final String LIFE_CARRIERS_Q = "LifeCarrierQList";
	  //public static final String REQ_Q_LIST = "reqQList";
	  public static final String QNAME = "qname";
	  public static final String MESSAGE_ID = "messageId";
	  public static final String RIDERS = "riders";
	  public static final String RIDER_ID = "riderId";
	  public static final String RIDER_NAME = "riderName";
	  public static final String RIDER_PREMIUM_AMOUNT = "riderPremiumAmount";
	  public static final String RIDER_DEPENDANT = "dependant";
	  public static final String RIDER_TYPE = "riderType";
	  public static final String RIDER_GROUP_ID = "riderGroupId";
	  public static final String RIDER_STATUS = "riderStatus";
	  public static final String PARAM = "param";
	  public static final String QUERY = "query";
	  public static final String PREMIUM_CONFIG = "premiumConfig";
	  public static final String RIDER_CONFIG = "riderConfig";
	  public static final String QUERY_DETAILS = "queryDetails";
	  public static final String PARAM_DEFAULT_VALUE = "defaultVal";
	  public static final String PARAM_DEFAULT_VALUE_STATUS = "defaultValStatus";
	  public static final String PARAM_NAME = "name";
	  public static final String PARAM_ABS_SA = "absSA";
	  public static final String PARAM_MIN_SA = "minSA";
	  public static final String PARAM_MAX_SA = "maxSA";
	  public static final String PARAM_MAX_TERM = "maxTerm";
	  public static final String PARAM_SA = "sumInsured";
	  public static final String PARAM_POLICY_TERM = "policyTerm";
	  public static final String PARAM_LIST = "list";
	  public static final String MIN_ALLOWED_PREMIUM = "minAllowedPremium";
	  public static final String PRODUCT_SA_LIST = "sumAssuredList";
	  
	  public static final String PRODUCT_RATINGS_QUERY 		=   " select p.DefaultRiskType,p.products AS products from ProductData p where "
															  + " p.documentType='LifeCategoryRating'"
															  + " and p.businessLineId=1"
															  + " and p.term=$1" 
															  + " and p.gender=$2" 
															  + " and p.healthCond=$3"
															  +	" and p.tobaccoAddicted=$4" 
															  +	" and p.minAnnualIncome<=$5" 
															  + " and p.annualIncome>=$5"  
															  + " and p.minAge<=$6"  
															  + " and p.age>=$6"  
															  + " and p.sumAssured<=$7"  
															  + " and p.maxSumAssured>=$7" 
																;
	  
	  public static final String PREMIUM_RATE = "premiumRate";
	  public static final String PREMIUM_RATE_LIST = "premiumRateList";
	  public static final String HIGHER_PREMIUM_RATE = "maxPremiumRate";
	  public static final String LOWER_PREMIUM_RATE = "minPremiumRate";
	  public static final String RIDER_SA_PERCENTAGE = "sumInsuredPercent";
	  public static final String RIDER_SA = "sumInsured";
	  public static final String RIDER_MAX_SA_PREMIUM_RATE = "riderMaxSAPremiumRate";
	  public static final String RIDER_MIN_SA_PREMIUM_RATE = "riderMinSAPremiumRate";
	  public static final String RIDER_PREMIUM_RATE = "riderPremiumRate";
	  public static final String RIDER_MAX_ALLOW_SA = "maxAllowedSA";
	  public static final String RIDER_MAX_ALLOW_PREMIUM = "maxAllowedPremium";
	  public static final String RIDER_PREMIUM_DISCOUNT = "premiumDiscount";
	  public static final String RIDER_MAX_ALLOW_BASEPREMIUM_PERCENTAGE = "maxAllowedBasePremiumPercent";
	  public static final String RIDER_ABS_SA = "absSA";
	  public static final String RIDER_MIN_SA = "minSA";
	  public static final String RIDER_MAX_SA = "maxSA";
	  public static final String RIDER_MIN_SA_PREMIUM = "minSAPremium";
	  public static final String RIDER_MAX_SA_PREMIUM = "maxSAPremium";
	  public static final String RIDER_PREMIUM_CONFIG = "RiderPremiumConfig";
	  public static final String PRODUCT_PREMIUM_CONFIG = "ProductPremiumConfig";
	  public static final String PRODUCT_HIGHER_PREMIUM_CONFIG = "ProductHigherPremiumConfig";
	  public static final String PRODUCT_LOWER_PREMIUM_CONFIG = "ProductLowerPremiumConfig";
	  public static final String WHERE_CONDITION = "whereCondition";
	  public static final String INPUT_PARAM_ARRAY = "inputParamArray";
	  public static final String PRODUCT_PREMIUMRATE_QUERY =   " select p.premiumRate as premiumRate from ProductData p "
			  											   /*  + " where p.documentType='LifeProductPremium' "
															 + " and p.carrierId=$1"
															 + " and p.productId=$2"
															 + " and p.insuredAge=$3"
															 + " and p.gender=$4"
															 + " and p.tobaccoUsage=$5"
															 + " and p.productTerm=$6"
															 + " and p.minSumAssured<=$7"
															 + " and p.maxSumAssured>=$7"
															 + " and p.healthCondition=$8"*/
															 ;
	  public static final String RIDER_PREMIUMRATE_QUERY =     " select p.premiumRate as riderPremiumRate from ProductData p "
					  										/* + " where p.documentType='LifeRiderPremium' "
					  										 + " and p.carrierId=$1"
					  										 + " and p.productId=$2"
															 + " and p.riderId=$3"
															 + " and p.insuredAge=$4"
															 + " and p.gender=$5"
															 + " and p.tobaccoUsage=$6"
															 + " and p.term=$7"
															 + " and p.coverageTerm=$8"
															 + " and p.sumInsuredPercent=$9" */
															 ;
	  //added for Kotak
	  public static final String CARRIER_REQ_MAP_CONF = "carrierReqMapConf";
	  public static final String CARRIER_INPUT_REQUEST ="carrierInputRequest";
	  public static final String LOG_REQ ="logReq";
	  public static final String KOTAKLIFESOAPREQPROCESS="KOTAKSOAPSOAPREQPROCESS";
	  public static final String CARRIER_QUOTE_REQUEST="LifeQuoteRequest-";
	  public static final String PRODUCTID="productId";
	  public static final String CARRIER_QUOTE_REQ_MAP_CONF = "LifeQuoteReqMapConf";
	  public static final String CARRIER_RESPONSE = "LifeQuoteResponse";
	  public static final String CARRIER_LIFE_RES_CONF = "LifeQuoteResponse-";
	  public static final String QuotationNumber="";
	  public static final String BUSINESS_LINE_ID="businessLineId";
	  
	 
	  
	  
}