package com.idep.pospservice.util;

public class POSPServiceConstant {
	public static final String DOCUMENT_TYPE 					= "documentType";
	public static final String DOCUMENT_ID 					    = "documentId";
	public static final String REQUEST_TYPE 					= "requestType";
	public static final String DOCID_CONFIG						= "DocumentIDConfig";
	public static final String REQUESTFLAG 						= "reqFlag";
	public static final String FALSE 							= "False";
	public static final String TRUE 							= "True";	
	public static final String RES_CODE 					    = "responseCode";
	public static final String RES_MSG 					        = "message";
	public static final String RES_MSG_USERNOTEXIST 		    = "response message:1000-User Not Exist";
	public static final String RES_MSG_USEREXIST 		        = "response message:1006-User Exist";
	public static final String RES_DATA 					    = "data";
	public static final String ERROR_CONFIG_CODE 				= "errorCode";
	public static final String ERROR_CONFIG_MSG 				= "errorMessage";
	public static final String SUCC_CONFIG_CODE 				= "successCode";
	public static final String SUCC_CONFIG_MSG 					= "successMessage";
	public static final String RESPONSE_MESSAGES 				= "ResponseMessages";
	public static final String NORECORD_MESSAGES 				= "noRecordsMessage";
	public static final String NORECORD_CODE 					= "noRecordsCode";
	public static final String FAILURE_MESSAGES 				= "failureMessage";
	public static final String FAILURE_CODE 					= "failureCode";
	public static final String LOGIN_FAILED_CODE 				= "loginFailedCode";
	public static final String LOGIN_FAILED_MESSAGES			= "loginFailedMessage";
	public static final String USER_EXIST_MESSAGES 				= "userExistMessage";
	public static final String USER_EXIST_CODE 					= "userExistCode";
	public static final String POSP_SEQ_AD 		                = "SEQPOSPAD";
	public static final String POSP_SEQ_AG 		                = "SEQPOSPAG";
	public static final String POSP_SEQ_ROLE 		                = "SEQPOSPROLE";
	public static final String POSP_SEQ_GROUP 		                = "SEQPOSPGROUP";
	public static final String POSPAG_GROUPID		                = "NIPOSGROUP000";
	public static final String POSPAD_ID		                = "POSP00AD";
	public static final String POSPAG_ID		                = "NIPOS000";
	public static final String POSPAG_ROLEID		                = "NIPOSROLE000";
	public static final String DOC_CREATED		                = "doc_created";
	public static final String DOC_REPLACED		                = "doc_replaced";
	public static final String DOC_UPDATED                      = "doc_updated";
	public static final String POSP_USER_PROFILE                = "POSPUserProfile-";
	public static final String POSP_ADMIN_PROFILE               = "POSPAdminProfile-";
	public static final String USER_EXIST                       = "UserExist";
	public static final String SERVICE_DATE_FORMAT              = "dd/MM/yyyy hh:mm:ss";
	public static final String BLOCKED_MOBILES                  = "BlockedMobilesList";
	public static final String BLOCKED_MOBILES_CODE             = "blockedMobileCode";
	public static final String MOBILE_NO                        = "mobileNumber";
	public static final String OTP                              = "OTP";
	public static final String SMS                              = "SMS-";
	public static final String NO_RECORDS_CODE                  = "noRecordsCode";
	public static final String NO_RECORDS_MSG                   = "noRecordsMessage";
    public static final String CREATED_DATE_TIME                = "createdDateTime";
	public static final String EXPIRATION_TIME                  = "expirationTime"; 
	public static final String EXPIRED_OTP_CODE                 = "expiredOTPCode";
	public static final String EXPIRED_OTP_MSG                  = "expiredOTPMessage";
	public static final String ADMIN                            = "Admin";
	public static final String ROLEID                           = "Role-";
	public static final String GROPID                           = "Group-";
	public static final String STATUS                           = "status";
	public static final String STAGE                            = "stage";
	public static final String PROFILE_VERF                     = "isProfileVerified";
	public static final String POSPMENUCONFIG 				= "pospMenuConfig"; 
	public static final String POSPSCREENCONFIG 				= "pospScreenConfig";
	public static final String TRANING_COMP                     = "isTraningCompleted";
    public static final String LEAD_QUERRY                      = "SELECT id,first_name,last_name,phone_mobile,date_entered,agencyid_c FROM leads join leads_cstm on leads.id = leads_cstm.id_c where campaign_id = '59f9bb13-6a98-870c-f66d-5bffa9f88f6f'";
    public static final String MOD_QUERRY                       = "SELECT id,first_name,last_name,phone_mobile,date_entered,agencyid_c FROM leads join leads_cstm on leads.id = leads_cstm.id_c where agencyid_c=?";
	public static final String RES_CODE_SUCCESS					    = "1000";
	public static final String RES_MSG_SUCCESS 					        = "Success";
	public static final String READ 					        = "read";
	public static final String WRITE 					        = "write";
	public static final String DELETE 					        = "delete";
	public static final String ISACTIVE 					        = "isActive";
	public static final String MENUID 					        = "menuId";
	public static final String SUBMENUID 					        = "subMenuId";
	public static final String SUBMENU 					        = "subMenu";
	public static final String RES_CODE_FAIL					    = "1001";
	public static final String RES_MSG_FAIL 					        = "failure";
}  

